notifications:
  slack: hkuplgroup:7jiTM7QOayfuaA2tm7YgOhHa

branches:
  only:
    - master
    - develop
    - testsuite
    - ghc-7.10

language: java

env:
  #- GHCVER=7.4.2
  #- GHCVER=7.6.3
  #- GHCVER=7.8.3
  - CABALVER=1.22 GHCVER=7.10.1
  #- GHCVER=head
  # - >
  #   GHCVER=7.4.2
  #   MODE="-fsafe"

jdk:
  - oraclejdk8

# matrix:
#   allow_failures:
#     - env: GHCVER=head

before_install:
  # If $GHCVER is the one travis has, don't bother reinstalling it.
  # We can also have faster builds by installing some libraries with
  # `apt`. If it isn't, install the GHC we want from hvr's PPA along
  # with cabal-1.18.
  - |
    if [ $GHCVER = `ghc --numeric-version` ]; then
      # Try installing some of the build-deps with apt-get for speed.
      travis/cabal-apt-install --enable-tests $MODE
      export CABAL=cabal
    else
      # Install the GHC we want from hvr's PPA
      travis_retry sudo add-apt-repository -y ppa:hvr/ghc
      travis_retry sudo apt-get update
      travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
      export CABAL=cabal-$CABALVER
      export PATH=/opt/ghc/$GHCVER/bin:$PATH
    fi

  # Uncomment whenever hackage is down.
  # - mkdir -p ~/.cabal && cp travis/config ~/.cabal/config && $CABAL update
  - $CABAL update

  # Update happy when building with GHC head
  - |
    if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.3" ] || [ ${GHCVER%.*} = "7.10" ]; then
      travis_retry sudo apt-get install happy-1.19.5 alex-3.1.4
      # $CABAL install happy alex hspec-discover hspec
      # export PATH=$HOME/.cabal/bin:$PATH
      export PATH=/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
    fi

install:
  - $CABAL install --dependencies-only --enable-tests
  - $CABAL configure -flib-Werror --enable-tests $MODE

script:
  - make test2
